### ISSUE TITLE
Better Output Control

### ISSUE THREAD

**Issue by aliehanani** [360macky/dreamify#6]
Consider including other inputs to generate better quality. Inputs such as negative prompt, scheduler, inference steps, seed, ect.

**Comment by 360macky** [comment]
Hi @aliehanani!
Thank you for your feedback. I will add the advance options feature in the next release for the next week!

**Comment by 360macky** [comment]
🚀 New advanced features for prompts" available!

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/47821093/227742417-42f6d675-9ac0-4a35-809f-2aac2cb2dbd4.png">

**Comment by aliehanani** [comment]
So cool! Thanks for all your efforts. Cheers
