### ISSUE TITLE
issue even with api key

### ISSUE THREAD

**Issue by rossman22590** [360macky/dreamify#7]
![screenshot-dreamify-theta vercel app-2023 04 09-18_19_39](https://user-images.githubusercontent.com/6137292/230799206-e680d9c3-6e9e-4ce8-921d-66c0c49e9b78.png)

**Comment by 360macky** [comment]
Hi @rossman22590!

Can you provide more details about this issue? (Steps to reproduce the error)
I guess you're trying to use Dreamify from localhost if so can you also show me if there is an error in the console Developer Tools?

**Comment by rossman22590** [comment]
hard to i upload scripts to github go to vercel --> https://dreamify-theta.vercel.app/ check and see

**Comment by 360macky** [comment]
> hard to i upload scripts to github go to vercel --> https://dreamify-theta.vercel.app/ check and see

Verify that you established the environment variable of `REPLICATE_API_TOKEN` with your own key of Replicate API.

**Comment by rossman22590** [comment]
i have because it send the picture to replicate latest prompt was A sunset of Lima

**Comment by 360macky** [comment]
I just tried again and it works on Vercel. Can you check if there is other interference? I see that you have made many changes to the interface in your own version (and you have Docker), if you have a new idea you can comment on this issue.

**Comment by rossman22590** [comment]
just deleted it and still broken try it

**Comment by 360macky** [comment]
Sorry I can't help you without more information or investigation from the fork. If you have any other issue, don't hesitate in opening a new issue. Thank you Ross!
